services:
  - type: web
    name: vidyasetu-sih-backend
    env: python
    region: singapore   # closest to India
    plan: free
    buildCommand: pip install uv && uv sync && uv run python -m src.db.seed
    startCommand: uv run uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin003@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: DEBUG
        value: "false"
